name: Run All Tests
on: [push]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install shellcheck
        run: |
          scversion="stable"
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-${scversion}/shellcheck" /usr/bin/
          sudo chmod +x /usr/bin/shellcheck
          shellcheck --version
      - name: Run Linters
        run: ./scripts/run-linters.sh
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run Unit and Integration Tests
        run: ./scripts/run-tests.sh
  end-to-end-test:
    name: Run End to End Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run End to End Tests
        run: ./scripts/run-end-to-end-tests.sh
  docker-test:
    name: Run Docker Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker Tests
        run: ./scripts/run-docker-tests.sh
